// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import RespondToCommentController from './respond_to_comment_controller';

import ToastController from './toast_controller';

application.register('respond-to-comment', RespondToCommentController);

application.register('toast', ToastController);
