// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import ScrollToParentController from './scroll_to_parent_controller';

import ToastController from './toast_controller';

application.register('scroll-to-parent', ScrollToParentController);

application.register('toast', ToastController);
